### ISSUE TITLE
[BUG] Some variables have no effect

### ISSUE THREAD

**Issue by pat-s** [UdelaRInterior/ansible-role-jitsi-meet#20]
Thanks for this role!

While deploying a jitsi instance, I found out that the following variables have no effect with v4.0:

- jitsi_meet_welcomepage_title
- jitsi_meet_welcomepage_description
- jitsi_meet_welcomepage_title
- jitsi_meet_default_background
- jitsi_meet_css_file

Also some work on FF but not on Chrome.

No big deal in the end, just wanted to let you know.

**Comment by santiagomr** [comment]
Thanks for the report, I'm going to check it

**Comment by santiagomr** [comment]
@pat-s, I tried it just in case and all the variables are having effect.

I think you don't notice the impact, because you have the variable `jitsi_meet_customize_the_ui` set in `false` (default value), and in this way all the [ui_customization.yml](https://github.com/UdelaRInterior/ansible-role-jitsi-meet/blob/master/tasks/ui_customization.yml) tasks are skipped 
```yaml
- include: ui_customization.yml
  tags: jitsi_ui
  when: jitsi_meet_customize_the_ui | bool
```
This is correct? It's in these tasks and templates where the variables you mention will actually be used.

**Comment by pat-s** [comment]
> This is correct? It's in these tasks and templates where the variables you mention will actually be used.

Indeed! I had it set to `false` 🤦 

Sorry for taking your time with this one 🙏

**Comment by santiagomr** [comment]
No problem. Better something doubly checked than an unreported error.
